const KSupaBaseUrl = "https://imhhpdemzceqmsaqlkhs.supabase.co";
const KSupaBaseKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltaGhwZGVtemNlcW1zYXFsa2hzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTI4MTIxMiwiZXhwIjoyMDU0ODU3MjEyfQ.bKbmJ_zpctpFRhwCguEF9MLmVl6eHZg1YaiJ6Ylc5t0";
